import React,{useRef,useState} from 'react';
import {Check,FileText,ArrowLeft,Printer} from 'lucide-react';
import {useTheme} from '@/contexts/ThemeContext';
import {useTenantProfile} from '@/hooks/useTenantProfile';
import {useAuth} from '@/context/AuthContext';
import {useVaNiToast} from '@/components/common/toast/VaNiToast';
import {InlineLoader} from '@/components/common/loaders/UnifiedLoader';
import type {ContractWizardState,ContractType} from '../logic/state';
import {eventPreview} from './eventsModel';
import {lineMoney,moneyTotals,priced,cycleNames} from './moneyModel';
import {textOnBrand} from '@/pages/experience/model';
import './review.css';

type Step='agreement'|'coverage'|'services'|'money'|'delivery'|'events';
interface Props{state:ContractWizardState;relationship:ContractType;busy:boolean;error:string|null;onSave:()=>Promise<boolean>;onSubmit:()=>Promise<void>;onBack:()=>void;onEdit:(step:Step)=>void;onClose:()=>void;}
export default function ReviewPage(p:Props){
 const s=p.state;const {currentTheme,isDarkMode}=useTheme();const c=isDarkMode?currentTheme.darkMode.colors:currentTheme.colors;
 const {profile}=useTenantProfile();const {perspective}=useAuth();const {addToast}=useVaNiToast();
 const [buyerView,setBuyerView]=useState(false);const [ack,setAck]=useState(false);const [working,setWorking]=useState(false);const [error,setError]=useState('');const flight=useRef(false);
 const preview=eventPreview(s),totals=moneyTotals(s);const expenses=perspective==='expense';
 const provider=expenses?s.buyerName:profile?.business_name;const customer=expenses?profile?.business_name:s.buyerName;
 const format=(v:number)=>new Intl.NumberFormat(undefined,{style:'currency',currency:s.currency}).format(v);
 const date=(v:Date)=>Number.isFinite(v.getTime())?v.toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'}):'Date needs review';
 const plain=(v:unknown)=>typeof v==='string'?v.replace(/<[^>]*>/g,' ').replace(/&nbsp;/g,' ').trim():'';
 const services=preview.events.filter(e=>e.event_type==='service').length,payments=preview.events.filter(e=>e.event_type==='billing').length;
 const steps:[Step,string][]=[['agreement','Agreement'],['coverage','Coverage & services'],['money','Money'],['delivery','Delivery & acceptance'],['events','Events Preview']];
 const run=async(final:boolean)=>{if(flight.current||p.busy)return;setError('');if(final&&(!ack||preview.errors.length)){setError(!ack?'Confirm that you have reviewed this agreement.':preview.errors[0]);return;}flight.current=true;setWorking(true);try{if(final)await p.onSubmit();else{if(!await p.onSave())throw new Error('Save was not confirmed. Your entries are still here.');addToast({type:'success',title:'Draft saved',message:'You can return to this agreement later.'});}}catch(e){setError(e instanceof Error?e.message:'Could not complete the action. Please retry.');}finally{flight.current=false;setWorking(false);}};
 const origin=s.templateId?<div className="fr-origin"><FileText size={15}/><strong>Origin</strong><span>Template {s.templateId} · Selections carried into this agreement</span></div>:null;
 return <div className="fr-page" style={{'--fr-brand':c.brand.primary,'--fr-on':textOnBrand(c.brand.primary),'--fr-bg':c.utility.secondaryBackground,'--fr-paper':c.utility.primaryBackground,'--fr-text':c.utility.primaryText,'--fr-muted':c.utility.secondaryText,'--fr-border':c.utility.border,'--fr-error':c.semantic.error} as React.CSSProperties}>
  <aside className="fr-rail"><div className="fr-eyebrow">A NEW AGREEMENT</div><p>Turn a promise<br/>into a plan.</p><nav aria-label="Contract chapters">{steps.map(([step,label])=><button disabled={working||p.busy} key={step} onClick={()=>p.onEdit(step)}><i><Check size={12}/></i>{label}</button>)}<span aria-current="step"><i>6</i>Final review</span></nav></aside>
  <main className="fr-main"><button className="fr-back" disabled={working||p.busy} onClick={p.onClose}>← Contracts</button><header><div className="fr-eyebrow">6 OF 6 · FINAL REVIEW</div><h1>Ready for the other side of the table.</h1><p>Check the document as seller or buyer, then choose the next lifecycle action.</p></header>
   <div className="fr-layout"><div className="fr-content">{origin}<div className="fr-docbar"><div><h2>Contract document</h2><p>One agreement. A relevant view for each party.</p></div><div className="fr-tabs"><button aria-pressed={!buyerView} onClick={()=>setBuyerView(false)}>Seller view</button><button aria-pressed={buyerView} onClick={()=>setBuyerView(true)}>{p.relationship==='partner'?'Partner view':'Buyer view'}</button><button aria-label="Print or save document as PDF" onClick={()=>window.print()}><Printer size={15}/></button></div></div>
   <article className="fr-document"><div className="fr-dochead"><div><div className="fr-eyebrow">{buyerView?'RECIPIENT COPY':'PROVIDER COPY'}</div><small>Reference assigned on creation</small></div><span className="fr-badge">{s.status}</span></div><h2>{s.contractName}</h2>{s.nomenclatureName&&<span className="fr-badge">{s.nomenclatureName}</span>}<div className="fr-parties"><div><small>SERVICE PROVIDER</small><strong>{provider||'Workspace name unavailable'}</strong></div><div><small>{p.relationship==='partner'?'CONTRACTING PARTNER':'CUSTOMER'}</small><strong>{customer||'Workspace name unavailable'}</strong></div></div>{origin}
    <section><h3>Term & scope</h3><p>{date(s.startDate)} to {date(preview.end)} · {s.durationValue} {s.durationUnit}</p>{s.description&&<p>{s.description}</p>}<p>{s.coverageTypes.length?s.coverageTypes.map(t=>`${t.resource_name} × ${t.unit_count ?? 'Not specified'}`).join(' · '):'Service-based agreement — no equipment attachment'}</p>{s.gracePeriodValue>0&&<p>Grace period: {s.gracePeriodValue} {s.gracePeriodUnit}</p>}</section>
    <section><h3>Agreed commitments</h3>{s.selectedBlocks.map((b,i)=><div className="fr-line" key={`${b.id}-${i}`}><div><strong>{b.name}</strong><p>{b.coverageTypeName||'Whole agreement'} · {b.unlimited?'Ongoing commitment':priced(b)?`${b.quantity} ${b.categoryId==='service'?'visits':'items'}`:'Agreement content'}{b.serviceCycleDays?` · every ${b.serviceCycleDays} days`:''}</p>{plain(b.categoryId==='text' ? b.config?.content || b.description : b.description)&&<p>{plain(b.categoryId==='text' ? b.config?.content || b.description : b.description)}</p>}{!buyerView&&<small>{b.isFlyBy?'FlyBy · this agreement only':'Catalog Studio'}</small>}</div><div><strong>{priced(b)?format(lineMoney(b,s).base):'Included'}</strong>{priced(b)&&<small>before tax</small>}</div></div>)}</section>
    <section><h3>Price & payment</h3>{[['Subtotal before tax',totals.baseSubtotal],['Discount',-totals.discountTotal],['Tax',totals.taxTotal]].map(([label,amount])=><div className="fr-totalrow" key={label}><span>{label}</span><strong>{format(Number(amount))}</strong></div>)}<div className="fr-totalrow fr-grand"><strong>Contract total</strong><strong>{format(totals.grandTotal)}</strong></div><p>{s.paymentMode==='emi'?`${s.emiMonths} monthly instalments`:s.paymentMode==='prepaid'?'One upfront payment':s.selectedBlocks.filter(priced).map(b=>`${b.name}: ${cycleNames[b.cycle]||b.cycle}`).join(' · ')}</p><p>{services} service events · {payments} payment events</p></section>
    <section><h3>Delivery & acceptance</h3><p>{s.evidencePolicyType==='none'?'No additional verification':s.evidencePolicyType==='upload'?'Photos or documents required':`Forms: ${s.evidenceSelectedForms.map(f=>f.name).join(', ')}`}</p><p>{s.acceptanceMethod==='auto'?'Activate without requesting acceptance.':s.acceptanceMethod==='payment'?'Acceptance follows the agreed payment.':'The receiving party reviews and signs off the proposal.'}</p><p>Contact: {s.buyerContactPersonName||s.buyerName}</p></section>
    {buyerView ? <section className="fr-recipient"><h3>Your agreement at a glance</h3><p>Prepared for {customer}. Your agreed amount is <strong>{format(totals.grandTotal)}</strong>.</p><h3>What happens next</h3><p>{s.acceptanceMethod==='signoff'?'Review the scope and dates, then accept or request changes through your contract link.':s.acceptanceMethod==='payment'?'Review the agreement and complete the agreed acceptance payment through your contract link.':'This agreement will be activated by the provider without requesting your sign-off.'}</p><p>Your CNAK and contract reference will be available after submission.</p><p>Recipient preview — acceptance and payment actions become available through the shared contract.</p></section> : <section className="fr-provider"><h3>Provider preparation · internal copy</h3><div className="fr-totalrow"><span>Delivery plan</span><strong>{services} service events</strong></div><div className="fr-totalrow"><span>Collection plan</span><strong>{payments} payment events</strong></div><p>Attached units: {s.equipmentDetails.filter(d=>!d.specifications?.placeholder).length}. {s.allowBuyerToAdd?'The recipient can complete the remaining asset details.':'Asset details are managed by your workspace.'}</p><h3>Commitment sources</h3>{s.selectedBlocks.map((b,i)=><p key={`${b.id}-source-${i}`}><strong>{b.name}</strong> · {b.isFlyBy?'FlyBy, specific to this agreement':'Catalog Studio'}{priced(b)?` · ${cycleNames[b.cycle]||b.cycle}`:''}</p>)}<p>After submission, check the returned status and CNAK before sharing. This preparation section is omitted from the recipient copy.</p></section>}
   </article><section className="fr-actions"><h3>Need to change something?</h3><div>{[...steps,['services','Services'] as [Step,string]].map(([key,label])=><button key={key} onClick={()=>p.onEdit(key)}>{label}</button>)}</div><p>Draft → <strong>{s.acceptanceMethod==='auto'?'Active after confirmation':'Pending acceptance'}</strong></p><label><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/>I've reviewed the document, scope, money and events.</label>{(error||p.error)&&<p role="alert">{error||p.error}</p>}</section></div>
   <aside className="fr-summary"><div className="fr-eyebrow">YOUR AGREEMENT <FileText size={16}/></div><h2>{s.contractName}</h2><p>With {s.buyerName}</p><dl><dt>Your role</dt><dd>{expenses?'Receiving · Money Out':'Delivering · Money In'}</dd><dt>Term</dt><dd>{s.durationValue} {s.durationUnit}</dd><dt>Coverage</dt><dd>{s.coverageTypes.length?s.coverageTypes.map(t=>t.resource_name).join(', '):'Service-based'}</dd><dt>Commitments</dt><dd>{s.selectedBlocks.length}</dd><dt>Service / payment events</dt><dd>{services} / {payments}</dd></dl><div className="fr-summary-total"><small>Contract value · {expenses?'Money Out':'Money In'}</small><strong>{format(totals.grandTotal)}</strong><small>Including configured tax</small></div><p><strong>Manual, by design.</strong><br/>You can create, schedule and manage this agreement without VaNi credits.</p></aside></div>
  </main><footer className="fr-footer"><div><strong>{s.contractName}</strong><small>Draft · Explicit lifecycle transition</small></div><div><button disabled={working||p.busy} onClick={p.onBack}><ArrowLeft size={14}/>Back</button><button disabled={working||p.busy} onClick={()=>void run(false)}>Save draft</button><button className="fr-primary" disabled={working||p.busy} onClick={()=>void run(true)}>{working||p.busy?<InlineLoader text="Saving…"/>:s.acceptanceMethod==='auto'?'Confirm agreement →':'Create proposal →'}</button></div></footer>
 </div>;
}
