import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
const compiled=ts.transpileModule(readFileSync(new URL('./entry.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}});
const {safeDestination,entryDestination,rememberDestination,consumeDestination}=await import(`data:text/javascript;base64,${Buffer.from(compiled.outputText).toString('base64')}`);
const full={completed:true,lite:false,owner:true};
assert.equal(entryDestination(full),'/experience');
assert.equal(entryDestination({...full,lite:true,completed:false}),'/ops/cockpit');
assert.equal(entryDestination({...full,completed:false}),'/onboarding');
assert.equal(entryDestination({completed:false,lite:false,owner:false}),'/onboarding-pending');
assert.equal(entryDestination({...full,completed:false},'/contracts/123'),'/onboarding');
assert.equal(entryDestination(full,'/contracts/123?tab=events#schedule'),'/contracts/123?tab=events#schedule');
for(const value of ['https://evil.test','//evil.test','/\\evil.test','/%2f%2fevil.test','/%5cevil.test','/login','/auth/google-callback','/forgot-password','/reset-password','/onboarding-pending','/start/business','/select-tenant','/a/../login',null]) assert.equal(safeDestination(value),null,String(value));
const store=new Map();globalThis.sessionStorage={getItem:k=>store.get(k)??null,setItem:(k,v)=>store.set(k,v),removeItem:k=>store.delete(k)};
rememberDestination('/contracts/123?tab=events');
assert.equal(consumeDestination(),'/contracts/123?tab=events');assert.equal(consumeDestination(),null);
rememberDestination('/contracts/old');assert.equal(consumeDestination(Date.now()+31*60*1000),null);
store.set('contractnest_auth_redirect','/contracts/review/abc');assert.equal(consumeDestination(),'/contracts/review/abc');
store.set('contractnest_entry_intent','bad json');assert.equal(consumeDestination(),null);
globalThis.sessionStorage={getItem:()=>{throw new Error('blocked');},setItem:()=>{throw new Error('blocked');}};
assert.doesNotThrow(()=>rememberDestination('/contracts/123'));assert.equal(consumeDestination(),null);
console.log('PASS: Full/Lite/owner/member entry; deep-link query/hash; unsafe/auth-loop rejection; intent single-use/expiry/legacy/storage errors.');
