import React,{useState} from 'react';
import CommitmentEditor from '@/components/contracts/ContractWizard/experience/CommitmentEditor';
import type {ConfigurableBlock} from '@/components/catalog-studio';
import SafeHtml from '@/components/catalog-studio/SafeHtml';
import type {RfpDraft,Requirement} from './model';
import '@/components/contracts/ContractWizard/experience/services.css';
import './proposal-offers.css';
export type ProposalBlock=ConfigurableBlock & {requirementId?:string};
export const proposalTotal=(blocks:ProposalBlock[])=>blocks.reduce((sum,b)=>sum+(b.categoryId==='text'||b.config?.complimentary?0:Math.round((b.config?.customPrice??b.price)*(b.unlimited?1:b.quantity)*100)),0)/100;
export function itemErrors(b:ProposalBlock,d:RfpDraft){
 const errors:string[]=[];const price=b.config?.customPrice??b.price;
 if(!b.name.trim())errors.push('Enter a name for this item.');
 if(b.categoryId==='text'&&!b.description?.replace(/<[^>]*>/g,'').replace(/&nbsp;/g,' ').trim())errors.push('Explain your terms or what you cannot include.');
 if(!Number.isInteger(b.quantity)||b.quantity<1)errors.push('Enter a positive whole quantity.');
 if(b.categoryId!=='text'&&(!Number.isFinite(price)||price<0||(!price&&!b.config?.complimentary)))errors.push('Enter a price or mark this item complimentary.');
 if(b.requirementId&&!d.blocks.some(r=>r.id===b.requirementId))errors.push('Choose the requested work this item answers.');
 if(d.coverage.length&&!d.coverage.some(c=>c.id===b.coverageTypeId))errors.push('Choose what this item covers.');
 const requirement=d.blocks.find(r=>r.id===b.requirementId);
 if(requirement?.coverageIds.length&&b.coverageTypeId&&!requirement.coverageIds.includes(b.coverageTypeId))errors.push('Choose coverage belonging to this requested work.');
 return errors;
}
export function proposalBlockErrors(blocks:ProposalBlock[],d:RfpDraft){
 const errors=blocks.flatMap(b=>itemErrors(b,d).map(e=>`${b.name||'Your item'}: ${e}`));
 for(const r of d.blocks)if(!blocks.some(b=>b.requirementId===r.id))errors.push(`“${r.name}” still needs your offer or an explanation of what you cannot include.`);
 if(!blocks.length&&!d.blocks.length)errors.push('Add the work you propose to deliver.');
 return errors;
}
export function createOffer(d:RfpDraft,type:string,r?:Requirement,coverageId?:string):ProposalBlock{
 const c=d.coverage.find(c=>c.id===coverageId);
 return {id:'proposal-'+crypto.randomUUID(),requirementId:r?.id,name:r?(type==='text'&&r.type!=='text'?`Exclusion: ${r.name}`:r.name):'',description:'',icon:'FileText',categoryId:type==='session'?'service':type,categoryName:({service:'Service',spare:'Spare Parts',session:'Group Session',text:'Text'} as Record<string,string>)[type],categoryColor:'#285f48',isFlyBy:true,flyByType:type==='session'?'service':type,quantity:r?.quantity||1,unlimited:r?.unlimited||false,price:0,totalPrice:0,currency:d.currency,cycle:'prepaid',coverageTypeId:c?.id,coverageTypeName:c?.name,...(type!=='text'&&r?.serviceCycleDays?{serviceCycleDays:r.serviceCycleDays}:{}),config:{showDescription:true,...(type==='session'?{audience:'group' as const}:{})}};
}
const colors={utility:{primaryText:'#243b35',secondaryText:'#667971'},brand:{primary:'#285f48'},semantic:{error:'#b42318',success:'#285f48',warning:'#9b6500'}};
export default function ProposalBlocks({draft,blocks,onChange,disabled=false,readOnly=false,onEditing,onError}: {draft:RfpDraft;blocks:ProposalBlock[];onChange:(v:ProposalBlock[])=>void;disabled?:boolean;readOnly?:boolean;onEditing?:(v:boolean)=>void;onError?:(message:string)=>void}){
 const [editing,setEditing]=useState<string|null>(null),[newId,setNewId]=useState<string|null>(null),[choices,setChoices]=useState<Record<string,string>>({}),[extra,setExtra]=useState(false);
 const [original,setOriginal]=useState<ProposalBlock|null>(null);
 function edit(id:string|null){setOriginal(id?blocks.find(b=>b.id===id)||null:null);setEditing(id);onEditing?.(!!id);}
 function cancel(){if(newId)onChange(blocks.filter(b=>b.id!==newId));else if(original)onChange(blocks.map(b=>b.id===original.id?original:b));setNewId(null);edit(null);}
 function add(type:string,r?:Requirement){const ids=r?r.coverageIds:draft.coverage.map(c=>c.id);const coverage=ids.length===1?ids[0]:choices[r?.id||'extra'];if(draft.coverage.length&&!coverage){onError?.('Choose what this offer covers first.');return;}const b=createOffer(draft,type,r,coverage);onChange([...blocks,b]);setNewId(b.id);edit(b.id);}
 function coveragePicker(key:string,ids:string[]){return ids.length>1?<label className="rfp-field">Choose what this offer covers<select value={choices[key]||''} onChange={e=>setChoices({...choices,[key]:e.target.value})}><option value="">Select equipment, facility or service</option>{draft.coverage.filter(c=>ids.includes(c.id)).map(c=><option key={c.id} value={c.id}>{c.name} × {c.quantity}</option>)}</select><small>Create another offer when a covered item needs a different price or plan.</small></label>:null;}
 return <div className="sv-page rfp-proposal-work" style={{'--ag-bg':'#f7f8f5','--ag-panel':'white','--ag-line':'#dce3da','--ag-text':'#243b35','--ag-muted':'#667971','--ag-brand':'#285f48','--ag-onbrand':'white','--ag-error':'#b42318'} as React.CSSProperties}>
 {!readOnly&&<><h3>Your proposed work</h3><p>Start with what the buyer requested. We carry its coverage into your offer. You set your price and can propose a different delivery plan.</p>{draft.blocks.map(r=>{const offers=blocks.filter(b=>b.requirementId===r.id&&b.id!==newId);return <section className="offer-request" key={r.id} tabIndex={-1} data-offer-issue={!offers.length||undefined}><span className="rfp-tag">{offers.length?'Offer added':'Your response needed'}</span><h4>{r.name}</h4><p>{r.coverageIds.map(id=>{const c=draft.coverage.find(c=>c.id===id);return c?`${c.name} × ${c.quantity}`:'Coverage unavailable';}).join(', ')}</p><p>Requested: {r.unlimited?'on demand':`${r.quantity} ${r.type==='spare'?'items':'occurrences'}`}{r.serviceCycleDays?` · every ${r.serviceCycleDays} days`:''}</p><SafeHtml html={r.description}/><fieldset disabled={disabled||!!editing}>{coveragePicker(r.id,r.coverageIds)}<div className="rfp-row"><button type="button" className="rfp-button primary" onClick={()=>add(r.type,r)} disabled={r.coverageIds.length>1&&!choices[r.id]}>{offers.length?'Add another offer':'Add your offer'}</button>{r.type!=='text'&&<button type="button" className="rfp-button" onClick={()=>add('text',r)} disabled={r.coverageIds.length>1&&!choices[r.id]}>Explain an exclusion</button>}</div></fieldset></section>;})}</>}
 {blocks.map(b=>{const requirement=draft.blocks.find(r=>r.id===b.requirementId),problems=itemErrors(b,draft);return <article className="rfp-unit offer-item" key={b.id} data-offer-issue={problems.length>0||undefined} tabIndex={-1}><span className="rfp-tag">{b.categoryId==='text'?'Terms & exclusions':b.categoryName}</span><h3>{b.name||'Your additional work'}</h3><p><strong>{requirement?`Your offer for: ${requirement.name}`:'Additional work'}</strong><br/>Covers: {b.coverageTypeName||'Choose coverage below'}</p>
 {!readOnly&&<details open={!b.coverageTypeId||(!b.requirementId&&draft.blocks.length>0)}><summary>Change which requested work this answers</summary><fieldset disabled={disabled}><label className="rfp-field">Requested work<select value={b.requirementId||''} onChange={e=>{const r=draft.blocks.find(x=>x.id===e.target.value),c=r?.coverageIds.length===1?draft.coverage.find(c=>c.id===r.coverageIds[0]):undefined;onChange(blocks.map(x=>x.id===b.id?{...x,requirementId:e.target.value,...(c?{coverageTypeId:c.id,coverageTypeName:c.name}:{})}:x));}}><option value="">Additional work, outside the request</option>{draft.blocks.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label className="rfp-field">What this covers<select value={b.coverageTypeId||''} onChange={e=>onChange(blocks.map(x=>x.id===b.id?{...x,coverageTypeId:e.target.value,coverageTypeName:draft.coverage.find(c=>c.id===e.target.value)?.name}:x))}><option value="">{draft.coverage.length?'Select coverage':'Whole agreement'}</option>{draft.coverage.map(c=><option key={c.id} value={c.id}>{c.name} × {c.quantity}</option>)}</select></label></fieldset></details>}
 {editing===b.id?<CommitmentEditor proposalMode key={b.id} instance={b} colors={colors} isDarkMode={false} currency={draft.currency} checked expanded flyBy priced={b.categoryId!=='text'} mode="contract" durationMonths={draft.months} coverageUnitCount={draft.coverage.find(c=>c.id===b.coverageTypeId)?.quantity} onSaved={()=>{setNewId(null);edit(null);}} saveLabel="Save this item" cancelLabel="Cancel editing" onValidationError={onError} validateBeforeSave={candidate=>itemErrors({...candidate,requirementId:b.requirementId,coverageTypeId:b.coverageTypeId},draft)[0]} onToggle={()=>{}} onToggleExpand={cancel} onUpdate={patch=>{const saved={...b,...patch,requirementId:b.requirementId,coverageTypeId:b.coverageTypeId,coverageTypeName:b.coverageTypeName};onChange(blocks.map(x=>x.id===b.id?{...saved,totalPrice:proposalTotal([saved])}:x));}}/>:<><SafeHtml html={b.description}/><p>{b.quantity} {b.config?.audience==='group'?'sessions':b.categoryId==='service'?'visits':'items'}{b.serviceCycleDays?` · every ${b.serviceCycleDays} days`:''} · {b.cycle}</p><strong>{b.categoryId==='text'?'Terms / explanation':`${draft.currency} ${proposalTotal([b]).toLocaleString()}`}</strong>{!readOnly&&<><div className="rfp-row"><button type="button" className="rfp-button primary" disabled={disabled||!!editing} onClick={()=>edit(b.id)}>Edit this item</button><button type="button" className="rfp-button" disabled={disabled||!!editing} onClick={()=>onChange(blocks.filter(x=>x.id!==b.id))}>Remove</button></div>{problems.length>0&&<p className="rfp-error" role="alert">{problems.join(' ')}</p>}</>}</>}
 </article>;})}
 {!readOnly&&<section className="offer-extra"><button type="button" className="rfp-button" disabled={disabled||!!editing} onClick={()=>setExtra(!extra)}>+ Add additional work</button>{extra&&<fieldset disabled={disabled||!!editing}><p>Use this for work or terms the buyer did not request.</p>{coveragePicker('extra',draft.coverage.map(c=>c.id))}<div className="rfp-row">{Object.entries({service:'Service',spare:'Materials & spares',session:'Group sessions',text:'Terms & exclusions'}).map(([type,label])=><button type="button" className="rfp-button" key={type} onClick={()=>add(type)} disabled={draft.coverage.length>1&&!choices.extra}>{label}</button>)}</div></fieldset>}</section>}
 </div>;
}
