import React, { useEffect, useRef, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { useAuth } from '@/context/AuthContext';
import { useTheme } from '@/contexts/ThemeContext';
import api from '@/services/api';
import { API_ENDPOINTS } from '@/services/serviceURLs';
import assetRegistryService from '@/services/assetRegistryService';
import resourcesService from '@/services/resourcesService';
import EquipmentFormDialog from '@/pages/equipment-registry/EquipmentFormDialog';
import type { AssetFormData } from '@/types/assetRegistry';
import { useNomenclatureTypes } from '@/hooks/queries/useNomenclatureTypes';
import { useContactList } from '@/hooks/useContacts';
import { RichTextEditor } from '@/components/ui/RichTextEditor';
import SafeHtml from '@/components/catalog-studio/SafeHtml';
import ChecklistRow from '@/components/contracts/ContractWizard/steps/serviceBlocksChecklist/ChecklistRow';
import { PageLoader, InlineLoader } from '@/components/common/loaders/UnifiedLoader';
import { useVaNiToast } from '@/components/common/toast/VaNiToast';
import { currencyOptions } from '@/utils/constants/currencies';
import { RFP_KEY, newDraft, validate, restore, commitmentSummary, type RfpDraft, type Family } from './model';
import { persistDraft, unwrap } from './persistence';
import './rfp-buyer.css';

const steps=['The need','Questions for vendors','Terms & money','Invite vendors','Review'];
const headings=['Find the right service partner.','Get answers you can compare.','Set clear terms from the start.','Bring the right people to the table.','Ready for the other side.'];
const errorText=(e:any)=>typeof e?.response?.data?.error==='string'?e.response.data.error:e?.response?.data?.error?.message||e.message||'Request failed';
const uid=()=>crypto.randomUUID();

export default function RfpBuyerPage({list=false}:{list?:boolean}) {
 const {currentTenant,isLive,perspective}=useAuth(); const {id}=useParams();
 if(!currentTenant?.id||typeof isLive!=='boolean'||perspective!=='expense')return <div className="rfp-buyer"><h1>Open the buyer workspace</h1><p>Choose the Expense perspective and the intended workspace before preparing an RFP.</p><Link to="/requests">Back to Requests</Link></div>;
 return <RfpWorkspace key={`${currentTenant.id}:${isLive}:${id||'new'}:${list}`} tenantId={currentTenant.id} live={isLive} id={id} list={list}/>;
}
function RfpWorkspace({tenantId,live,id,list}:{tenantId:string;live:boolean;id?:string;list:boolean}) {
 const {currentTheme,isDarkMode}=useTheme();const colors=isDarkMode?currentTheme.darkMode.colors:currentTheme.colors;
 const {addToast}=useVaNiToast();const navigate=useNavigate();
 const [draft,setDraft]=useState(()=>newDraft(tenantId,live,currencyOptions.find(c=>c.isDefault)?.code||''));
 const [record,setRecord]=useState<any>(null),[loading,setLoading]=useState(!!id),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[fatal,setFatal]=useState(''),[issues,setIssues]=useState<string[]>([]);
 const [modal,setModal]=useState<'labels'|'registry'|'coverage'|null>(null),[expanded,setExpanded]=useState<string|null>(null);
 const [assetPage,setAssetPage]=useState(0),[contactSearch,setContactSearch]=useState(''),[contactPage,setContactPage]=useState(1),[page,setPage]=useState(1);
 const [newCoverage,setNewCoverage]=useState({name:'',location:'',quantity:1,family:'equipment' as Family});
 const [prospect,setProspect]=useState({name:'',email:''});
 const [register,setRegister]=useState<'equipment'|'asset'|null>(null),[registering,setRegistering]=useState(false);
 const registryFlight=useRef(false);
 const inFlight=useRef(false),alive=useRef(true),uncertain=useRef(false),createKey=useRef(uid()),dialog=useRef<HTMLDialogElement>(null);
 const nomenclatures=useNomenclatureTypes();
 const contacts=useContactList({classifications:['vendor'],status:'active',search:contactSearch||undefined,page:contactPage,limit:20});
 useEffect(()=>{const timer=setTimeout(()=>contacts.updateFilters({classifications:['vendor'],status:'active',search:contactSearch||undefined,page:contactPage,limit:20}),250);return()=>clearTimeout(timer);},[contactSearch,contactPage,contacts.updateFilters]);
 const assets=useQuery({queryKey:['rfp-registry',tenantId,live,assetPage],queryFn:()=>assetRegistryService.listAssets({offset:assetPage*20,limit:20,is_live:live}),enabled:modal==='registry'});
 const types=useQuery({queryKey:['rfp-registry-types',tenantId,live,register],queryFn:()=>resourcesService.getResourceTemplates({resource_type_id:register!,limit:500}),enabled:!!register});
 const drafts=useQuery({queryKey:['rfp-drafts',tenantId,live,page],enabled:list,queryFn:async()=>{
   const res=unwrap(await api.get(API_ENDPOINTS.CONTRACTS.LIST_WITH_FILTERS({record_type:'rfq',status:'draft',page,limit:10})));
   if(!Array.isArray(res.items))throw new Error('The request list returned an unexpected response.');
   const details=await Promise.all(res.items.map((c:any)=>api.get(API_ENDPOINTS.CONTRACTS.GET(c.id)).then(unwrap)));
   return {items:details.filter(c=>c.metadata?.[RFP_KEY]&&c.tenant_id===tenantId&&c.is_live===live),next:!!res.page_info?.has_next_page};
 }});
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 useEffect(()=>{if(!id)return;let cancelled=false;api.get(API_ENDPOINTS.CONTRACTS.GET(id)).then(unwrap).then(c=>{
   if(cancelled)return;if(c.tenant_id!==tenantId||c.is_live!==live||c.status!=='draft'||c.record_type!=='rfq')throw new Error('This request cannot be edited in this workspace, environment or status.');
   const restored=restore(c.metadata?.[RFP_KEY],tenantId,live);setRecord(c);setDraft(restored);
 }).catch(e=>{if(!cancelled)setFatal(errorText(e));}).finally(()=>{if(!cancelled)setLoading(false);});return()=>{cancelled=true;};},[id,tenantId,live]);
 useEffect(()=>{const before=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',before);return()=>window.removeEventListener('beforeunload',before);},[dirty]);
 useEffect(()=>{if(modal&&!dialog.current?.open)dialog.current?.showModal();},[modal]);
 const change=(patch:Partial<RfpDraft>)=>{setDraft(d=>({...d,...patch}));setDirty(true);};
 const fail=(message:string)=>{setIssues([message]);addToast({type:'error',title:'Not saved',message});};
 async function registerAsset(data:AssetFormData){
   if(registryFlight.current)return;
   registryFlight.current=true;setRegistering(true);
   try{
     const asset=await assetRegistryService.createAsset(data);
     if(!alive.current)return;
     if(!asset.id||asset.tenant_id!==tenantId||asset.is_live!==live)throw new Error('Registry save was not confirmed in this workspace. Check the registry before retrying.');
     change({coverage:[...draft.coverage,{id:uid(),name:asset.name,quantity:1,location:asset.location||'',family:asset.resource_type_id==='asset'?'facility':'equipment',resourceId:asset.asset_type_id||asset.template_id||null,registryId:asset.id}]});
     setRegister(null);void assets.refetch();
     addToast({type:'success',title:'Registered and added to your request',message:'One registered unit linked. Save your RFP draft to retain this coverage.'});
   }catch(e){if(alive.current){setRegister(null);addToast({type:'error',title:'Check registry before retrying',message:errorText(e)});}}
   finally{registryFlight.current=false;if(alive.current)setRegistering(false);}
 }
 async function save(next?:number){
   if(inFlight.current||uncertain.current)return;
   const errors=next===undefined?(!draft.title.trim()?['Give your request a name before saving.']:[]):validate(draft,draft.step);
   if(errors.length){setIssues(errors);return;}
   const snapshot={...draft,step:next??draft.step};inFlight.current=true;setBusy(true);setIssues([]);
   let savedId=record?.id;
   try{
     const confirmed=await persistDraft(api,snapshot,record,{get:API_ENDPOINTS.CONTRACTS.GET,update:API_ENDPOINTS.CONTRACTS.UPDATE},record?uid():createKey.current,()=>alive.current);
     savedId=confirmed.id;
     if(!alive.current)return;setRecord(confirmed);setDraft(snapshot);setDirty(false);
     addToast({type:'success',title:'RFP draft saved',message:'All sections saved. Nothing has been sent.'});
     if(!id)navigate(`/requests/rfp/${savedId}`,{replace:true});
   }catch(e:any){if(!alive.current)return;if(!record||savedId&&(!e.response||e.response.status>=500)){uncertain.current=true;setFatal('Save outcome needs checking. Open RFP Drafts in another tab before retrying, to avoid duplicate or stale writes.');}fail(errorText(e));}
   finally{inFlight.current=false;if(alive.current)setBusy(false);}
 }
 const field=(key:keyof RfpDraft,label:string,type='text',extra:Record<string,unknown>={})=><label className="rfp-field">{label}<input type={type} value={String(draft[key]??'')} onChange={e=>change({[key]:type==='number'?Number(e.target.value):e.target.value})} {...extra}/></label>;
 const rich=(key:'brief'|'terms'|'releaseTerms',label:string)=><RichTextEditor label={label} value={draft[key]} onChange={value=>change({[key]:value})} toolbarButtons={['bold','italic','underline','bulletList','orderedList','table']} minHeight={110}/>;
 const button=(label:string,action:()=>void,primary=false,disabled=false)=><button type="button" className={primary?'rfp-button primary':'rfp-button'} disabled={disabled||busy} onClick={action}>{label}</button>;
 function addBlock(type:string){const block:RfpDraft['blocks'][number]={id:uid(),name:'',description:'',icon:'Wrench',quantity:1,cycle:'prepaid',unlimited:false,price:0,currency:draft.currency,totalPrice:0,categoryName:type==='service'?'Service':type==='spare'?'Spare / material':'Terms',categoryColor:colors.brand.primary,isFlyBy:true,flyByType:type,coverageIds:[]};change({blocks:[...draft.blocks,block]});setExpanded(block.id);}
 function addRecipient(name:string,email:string,contactId:string|null){if(!name.trim()||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)){fail('A recipient needs a name and valid email.');return;}if(draft.invites.some(v=>v.email.toLowerCase()===email.toLowerCase())){fail('That email is already selected.');return;}change({invites:[...draft.invites,{id:uid(),name,email,contactId}]});setProspect({name:'',email:''});}
 const styles={'--rfp-ink':colors.utility.primaryText,'--rfp-muted':colors.utility.secondaryText,'--rfp-surface':colors.utility.secondaryBackground,'--rfp-bg':colors.utility.primaryBackground,'--rfp-brand':colors.brand.primary,'--rfp-line':colors.utility.primaryText+'25'} as React.CSSProperties;
 if(loading)return <PageLoader message="Opening your RFP draft"/>;
 if(list)return <main className="rfp-buyer" style={styles}><div className="rfp-row between"><div><small>BUYER WORKSPACE</small><h1>RFP drafts</h1><p>Structured requests, saved before inviting the other side.</p></div><Link className="rfp-button primary" to="/requests/rfp/new">New RFP →</Link></div><p className="rfp-note">Buyer release · sharing is not enabled until the vendor questionnaire flow is connected.</p>{drafts.isLoading?<PageLoader message="Loading RFP drafts"/>:drafts.isError?<div role="alert">{errorText(drafts.error)}{button('Retry',()=>void drafts.refetch())}</div>:<>{drafts.data?.items.map((c:any)=><Link key={c.id} className="rfp-paper rfp-draft" to={`/requests/rfp/${c.id}`}><strong>{c.name||c.title}</strong><span>{c.rfq_number||c.contract_number} · Draft</span><span>Continue →</span></Link>)}{!drafts.data?.items.length&&<p>No RFP drafts on this page. Older RFQ drafts stay in Requests.</p>}<div className="rfp-row">{button('Previous',()=>setPage(p=>p-1),false,page===1)}<span>Page {page}</span>{button('Next',()=>setPage(p=>p+1),false,!drafts.data?.next)}</div></>}<Link to="/requests">Existing Requests / RFQs</Link></main>;
 return <main className="rfp-buyer" style={styles}>
  <div className="rfp-shell"><aside className="rfp-rail"><Link to="/requests/rfp" onClick={e=>{if(dirty&&!window.confirm('Leave with unsaved changes?'))e.preventDefault();}}>← RFP drafts</Link><small>A NEW REQUEST</small><nav>{steps.map((name,i)=><button key={name} aria-current={draft.step===i?'step':undefined} disabled={busy||i>draft.step} onClick={()=>change({step:i})}><b>{i+1}</b>{name}</button>)}</nav><p>Manual, by design.<br/>Your scope. Your decision.</p></aside>
  <div className="rfp-main"><small>{draft.step+1} OF 5 · BUYER REQUEST</small><h1>{headings[draft.step]}</h1><p>Define the need clearly. Vendors bring their approach and price.</p>
  {fatal&&<div className="rfp-error" role="alert">{fatal} <Link target="_blank" to="/requests/rfp">Open saved drafts</Link></div>}{issues.length>0&&<div className="rfp-error" role="alert"><strong>Please check these details</strong><ul>{issues.map((x,i)=><li key={i}>{x}</li>)}</ul></div>}
  <fieldset disabled={busy||!!fatal} className="rfp-grid"><div className="rfp-stack">
  {draft.step===0&&<>
   <section className="rfp-paper"><h2>Describe the outcome, not the paperwork.</h2><div className="rfp-choices">{(['equipment','facility','service'] as Family[]).map(f=><button key={f} className={draft.family===f?'selected':''} aria-pressed={draft.family===f} onClick={()=>change({family:f})}>{f==='equipment'?'Equipment':f==='facility'?'Facilities':'Services'}</button>)}</div><div className="rfp-note rfp-row between"><div><small>INTENDED AGREEMENT · OPTIONAL</small><strong>{draft.nomenclature?.label||'Choose an agreement label'}</strong><p>{draft.nomenclature?.group||'Separate from what is covered.'}</p></div>{button(draft.nomenclature?'Change':'Choose label',()=>setModal('labels'))}</div><div className="rfp-fields">{field('title','What do you need? *')}{field('location','Where is the work? *')}{field('start','Preferred start date *','date')}{field('months','Expected duration (months) *','number',{min:1,max:120})}</div>{rich('brief','What does a good outcome look like? *')}</section>
   <section className="rfp-paper"><h2>What is covered?</h2><p>Multiple items. Registry-linked or described for this request.</p><div className="rfp-row">{button('Pick from registry',()=>setModal('registry'))}{button('+ Describe new coverage',()=>{setNewCoverage({name:'',quantity:1,location:draft.location,family:draft.family});setModal('coverage');})}</div>{draft.coverage.map(c=><article className="rfp-unit" key={c.id}><div className="rfp-row between"><div><h3>{c.name} × {c.quantity}</h3><p>{c.location}</p><span className="rfp-tag">{c.registryId?'Registry linked':'Request only'}</span></div>{button('Remove',()=>{if(draft.blocks.some(b=>b.coverageIds.includes(c.id))){fail('Unlink this coverage from its requirements before removing it.');return;}change({coverage:draft.coverage.filter(x=>x.id!==c.id)});})}</div></article>)}<div className="rfp-row">{button('Register equipment & add',()=>setRegister('equipment'))}{button('Register facility & add',()=>setRegister('asset'))}</div><p className="rfp-note">Described coverage stays request-only. Register & add opens the existing registry form and saves one actual unit to your registry only when you submit it. Services remain request-only.</p></section>
   <section className="rfp-paper"><h2>What should they propose for?</h2><p>Existing FlyBy block controls · service cadence and billing stay separate.</p><div className="rfp-row">{button('+ Service',()=>addBlock('service'))}{button('+ Spare / material',()=>addBlock('spare'))}{button('+ Terms',()=>addBlock('text'))}</div>{draft.blocks.map(b=><article className="rfp-unit" key={b.id}><h3>{b.name||'New requirement'}</h3><div className="rfp-row wrap">{draft.coverage.map(c=><label className="rfp-check" key={c.id}><input type="checkbox" checked={b.coverageIds.includes(c.id)} onChange={e=>change({blocks:draft.blocks.map(x=>x.id===b.id?{...x,coverageIds:e.target.checked?[...x.coverageIds,c.id]:x.coverageIds.filter(id=>id!==c.id)}:x)})}/>{c.name} ×{c.quantity}</label>)}</div><ChecklistRow colors={colors} isDarkMode={isDarkMode} currency={draft.currency} instance={b} checked flyBy mode="rfq" priced={b.flyByType!=='text'} expanded={expanded===b.id} durationMonths={draft.months} coverageUnitCount={draft.coverage.filter(c=>b.coverageIds.includes(c.id)).reduce((n,c)=>n+c.quantity,0)} onToggle={()=>setExpanded(b.id)} onToggleExpand={()=>setExpanded(expanded===b.id?null:b.id)} onUpdate={updates=>change({blocks:draft.blocks.map(x=>x.id===b.id?{...x,...updates}:x)})} onRemove={()=>change({blocks:draft.blocks.filter(x=>x.id!==b.id)})}/><p className="rfp-note">{commitmentSummary(b,draft)}. Quantity covers the linked units together, not per unit.</p></article>)}</section>
  </>}
  {draft.step===1&&<><section className="rfp-paper"><div className="rfp-row between"><h2>Ask once. Compare fairly.</h2>{button('+ Add question',()=>change({questions:[...draft.questions,{id:uid(),text:'',section:'Delivery',type:'text',required:true,eligibility:false}]}))}</div>{draft.questions.map((q,i)=>{const edit=(patch:Partial<typeof q>)=>change({questions:draft.questions.map(x=>x.id===q.id?{...x,...patch}:x)});return <article className="rfp-unit" key={q.id}><div className="rfp-fields"><label className="rfp-field">{i+1}. Question *<input value={q.text} onChange={e=>edit({text:e.target.value})}/></label><label className="rfp-field">Section<input value={q.section} onChange={e=>edit({section:e.target.value})}/></label><label className="rfp-field">Answer format<select value={q.type} onChange={e=>edit({type:e.target.value as any,eligibility:false})}>{[['text','Written answer'],['number','Number'],['yesno','Yes / No'],['file','Document']].map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label></div><label className="rfp-check"><input type="checkbox" checked={q.required} disabled={q.eligibility} onChange={e=>edit({required:e.target.checked})}/>Answer required</label><label className="rfp-check"><input type="checkbox" checked={q.eligibility} disabled={q.type!=='yesno'} onChange={e=>edit({eligibility:e.target.checked,required:true})}/>Eligibility condition — must answer Yes</label>{button('Remove',()=>change({questions:draft.questions.filter(x=>x.id!==q.id)}))}</article>})}<p className="rfp-note">Required answers and eligibility conditions are different. Document questions describe what the vendor will upload in the response release.</p></section><section className="rfp-paper"><h2>Tell vendors what matters.</h2><p>Proposed weights. No automatic winner.</p><div className="rfp-fields">{['Approach & delivery','Experience & capability','Commercial value'].map((label,i)=><label className="rfp-field" key={label}>{label} (%)<input type="number" min="0" max="100" value={draft.weights[i]} onChange={e=>change({weights:draft.weights.map((v,j)=>j===i?Number(e.target.value):v)})}/></label>)}</div></section></>}
  {draft.step===2&&<><section className="rfp-paper"><h2>Make the response rules clear.</h2><div className="rfp-fields"><label className="rfp-field">Quote currency *<select value={draft.currency} onChange={e=>change({currency:e.target.value,blocks:draft.blocks.map(b=>({...b,currency:e.target.value}))})}><option value="">Choose currency</option>{currencyOptions.map(c=><option key={c.code} value={c.code}>{c.code} · {c.name}{c.isDefault?' · Default':''}</option>)}</select></label>{field('budget','Indicative budget · optional','text')}{field('deadline','Proposals due by *','date')}{field('deadlineTime','Closing time · Asia/Kolkata *','time')}{field('questionsBy','Clarification questions due by *','date')}</div><label className="rfp-check"><input type="checkbox" checked={draft.shareBudget} onChange={e=>change({shareBudget:e.target.checked})}/>Share indicative budget</label>{rich('terms','Terms and expectations *')}</section><section className="rfp-paper"><h2>Is a bid security required?</h2><p>Vendor → buyer during bidding. Not a service advance.</p><div className="rfp-choices">{[['none','No bid security'],['declaration','Bid declaration'],['deposit','Bid security / EMD']].map(([v,t])=><button key={v} aria-pressed={draft.security===v} className={draft.security===v?'selected':''} onClick={()=>change({security:v as any})}>{t}</button>)}</div>{draft.security==='deposit'&&<>{field('securityAmount',`Fixed amount (${draft.currency}) *`)}{rich('releaseTerms','Release / refund conditions *')}<label className="rfp-check"><input type="checkbox" checked={draft.exemption} onChange={e=>change({exemption:e.target.checked})}/>Allow exemption requests with evidence</label></>}<label className="rfp-check"><input type="checkbox" checked={draft.performance} onChange={e=>change({performance:e.target.checked})}/>Performance security from the selected vendor after award</label>{draft.performance&&field('performancePct','Percentage of awarded value *')}<p className="rfp-note">This stores participation requirements, not a payment instruction or receipt. Catalog Studio’s advance deposit remains a buyer → provider commercial term.</p></section></>}
  {draft.step===3&&<section className="rfp-paper"><h2>Who should respond?</h2><p>Intended recipients only. No invitation is sent in this release.</p><label className="rfp-field">Search existing vendors<input value={contactSearch} onChange={e=>{setContactSearch(e.target.value);setContactPage(1);}}/></label>{contacts.loading?<InlineLoader text="Loading vendors"/>:contacts.error?<p role="alert">{String(contacts.error)}</p>:(contacts.contacts||[]).map((c:any)=>{const email=c.contact_channels?.find((x:any)=>(x.channel_type||'').toLowerCase()==='email')?.value||c.email||'';const name=c.company_name||c.name||c.displayName||[c.first_name,c.last_name].filter(Boolean).join(' ');return <div className="rfp-row between" key={c.id}><span>{name}<small>{email||'No email available'}</small></span>{button('Select',()=>addRecipient(name,email,c.id),false,!email||draft.invites.some(v=>v.contactId===c.id))}</div>})}<div className="rfp-row">{button('Previous vendors',()=>setContactPage(p=>p-1),false,contactPage===1)}{button('Next vendors',()=>setContactPage(p=>p+1),false,(contacts.contacts||[]).length<20)}</div><hr/><h3>Invite a new prospect</h3><div className="rfp-fields"><label className="rfp-field">Name<input value={prospect.name} onChange={e=>setProspect(p=>({...p,name:e.target.value}))}/></label><label className="rfp-field">Email<input type="email" value={prospect.email} onChange={e=>setProspect(p=>({...p,email:e.target.value}))}/></label></div>{button('Add prospect',()=>addRecipient(prospect.name,prospect.email,null))}{draft.invites.map(v=><article className="rfp-unit rfp-row between" key={v.id}><div><strong>{v.name}</strong><p>{v.email}</p><span className="rfp-tag">{v.contactId?'Existing vendor':'Prospect · request only'}</span></div>{button('Remove',()=>change({invites:draft.invites.filter(x=>x.id!==v.id)}))}</article>)}</section>}
  {draft.step===4&&<><article className="rfp-document"><small>REQUEST FOR PROPOSALS · DRAFT</small><h2>{draft.title}</h2><SafeHtml html={draft.brief}/><h3>Coverage & intended agreement</h3><p>{draft.nomenclature?.label||'Agreement label not specified'} · {draft.start} · {draft.months} months</p>{draft.coverage.map(c=><p key={c.id}>{c.name} × {c.quantity} · {c.location} · {c.registryId?'Registry linked':'Request only'}</p>)}<h3>Requested work</h3>{draft.blocks.map(b=><section key={b.id}><strong>{b.name}</strong><SafeHtml html={b.description}/><p>{commitmentSummary(b,draft)}</p></section>)}<h3>Questions to answer</h3><ol>{draft.questions.map(q=><li key={q.id}>{q.text} · {q.type}{q.required?' · required':''}{q.eligibility?' · eligibility: Yes required':''}</li>)}</ol><h3>How we will choose</h3><p>Approach {draft.weights[0]}% · Capability {draft.weights[1]}% · Commercial value {draft.weights[2]}%</p><h3>Terms & participation</h3><SafeHtml html={draft.terms}/><p>Quote in {draft.currency}. {draft.shareBudget&&draft.budget?`Indicative budget: ${draft.budget}.`:''}</p><p>{draft.security==='deposit'?`Bid security ${draft.currency} ${draft.securityAmount}`:draft.security==='declaration'?'Bid declaration required':'No bid security required'}</p>{draft.security==='deposit'&&<SafeHtml html={draft.releaseTerms}/>}<p>{draft.exemption&&draft.security==='deposit'?'Exemption requests allowed. ':''}{draft.performance?`Performance security after award: ${draft.performancePct}%.`:''}</p><h3>Respond by</h3><p>{draft.deadline} · {draft.deadlineTime} IST. Clarifications by {draft.questionsBy}.</p></article><p className="rfp-note">Review and save now. Sharing is intentionally unavailable until vendors can answer these questions and participation requirements. Nothing will be sent to the old quote-only page.</p></>}
  </div><aside className="rfp-summary"><small>YOUR REQUEST</small><h2>{draft.title||'Your request takes shape here'}</h2><span className="rfp-tag">Draft · not sent</span><dl><dt>Agreement label</dt><dd>{draft.nomenclature?.label||'Not selected'}</dd><dt>Term</dt><dd>{draft.months?draft.months+' months':'Not set'}</dd><dt>Covered items</dt><dd>{draft.coverage.length}</dd><dt>Requirements</dt><dd>{draft.blocks.length}</dd><dt>Questions</dt><dd>{draft.questions.length}</dd><dt>Recipients</dt><dd>{draft.invites.length}</dd></dl><p>One request. Independent proposals. No contract, event or payment is created.</p></aside></fieldset>
  <div className="rfp-footer"><div><strong>{record?.rfq_number||'RFP draft'}</strong><small>{dirty?'Unsaved changes':record?'Saved to your workspace':'Not yet saved'}</small></div><div className="rfp-row">{busy?<InlineLoader text="Saving and verifying draft"/>:<>{draft.step>0&&button('← Back',()=>change({step:draft.step-1}))}{button('Save draft',()=>void save(),false,!!fatal)}{draft.step<4?button('Save & continue →',()=>void save(draft.step+1),true,!!fatal):button('Save reviewed draft',()=>{const errs=[0,1,2,3].flatMap(i=>validate(draft,i));if(errs.length)setIssues(errs);else void save();},true,!!fatal)}</>}</div></div>
  </div></div>
  <dialog ref={dialog} onCancel={()=>setModal(null)} className="rfp-modal"><div className="rfp-row between"><h2>{modal==='labels'?'Contract family & agreement label':modal==='registry'?'Pick from your registry':'Describe new coverage'}</h2>{button('Close',()=>{dialog.current?.close();setModal(null);})}</div>
   {modal==='labels'&&(nomenclatures.isLoading?<InlineLoader/>:nomenclatures.isError?<p role="alert">Could not load agreement labels. {button('Retry',()=>void nomenclatures.refetch())}</p>:nomenclatures.data?.map(g=><section className="rfp-unit" key={g.group}><h3>{g.label}</h3><div className="rfp-row wrap">{g.items.map(n=>button(n.form_settings.short_name||n.display_name,()=>{change({nomenclature:{id:n.id,label:n.form_settings.short_name||n.display_name,group:g.label}});dialog.current?.close();setModal(null);},draft.nomenclature?.id===n.id))}</div></section>))}
   {modal==='registry'&&<>{assets.isLoading?<InlineLoader/>:assets.isError?<p role="alert">{errorText(assets.error)}{button('Retry',()=>void assets.refetch())}</p>:assets.data?.data.filter(a=>a.is_live===live&&a.tenant_id===tenantId&&a.is_active&&['equipment','asset'].includes(a.resource_type_id)).map(a=><section className="rfp-unit rfp-row between" key={a.id}><div><h3>{a.name}</h3><p>{a.location}</p></div>{button('Select',()=>{change({coverage:[...draft.coverage,{id:uid(),name:a.name,quantity:1,location:a.location||'',family:a.resource_type_id==='asset'?'facility':'equipment',resourceId:a.asset_type_id||a.template_id||null,registryId:a.id}]});dialog.current?.close();setModal(null);},false,draft.coverage.some(c=>c.registryId===a.id))}</section>)}<div className="rfp-row">{button('Previous',()=>setAssetPage(p=>p-1),false,assetPage===0)}{button('Next',()=>setAssetPage(p=>p+1),false,!assets.data?.pagination.has_more)}</div></>}
   {modal==='coverage'&&<><div className="rfp-fields"><label className="rfp-field">Name *<input value={newCoverage.name} onChange={e=>setNewCoverage(c=>({...c,name:e.target.value}))}/></label><label className="rfp-field">Location<input value={newCoverage.location} onChange={e=>setNewCoverage(c=>({...c,location:e.target.value}))}/></label><label className="rfp-field">Units *<input type="number" min="1" value={newCoverage.quantity} onChange={e=>setNewCoverage(c=>({...c,quantity:Number(e.target.value)}))}/></label><label className="rfp-field">Category<select value={newCoverage.family} onChange={e=>setNewCoverage(c=>({...c,family:e.target.value as Family}))}><option value="equipment">Equipment</option><option value="facility">Facilities</option><option value="service">Services</option></select></label></div>{button('Add to request',()=>{if(!newCoverage.name.trim()||!Number.isInteger(newCoverage.quantity)||newCoverage.quantity<1){addToast({type:'error',title:'Check coverage',message:'Enter a name and positive whole-number unit count.'});return;}change({coverage:[...draft.coverage,{...newCoverage,id:uid(),resourceId:null,registryId:null}]});dialog.current?.close();setModal(null);},true)}</>}
  </dialog>
  {register&&(types.isLoading?<InlineLoader text="Loading registry types"/>:types.isError?<div className="rfp-error" role="alert">Registry types could not load. {button('Retry',()=>void types.refetch())}{button('Cancel',()=>setRegister(null))}</div>:<EquipmentFormDialog isOpen mode="create" onClose={()=>{if(!registering)setRegister(null);}} registryMode={register==='asset'?'entity':'equipment'} defaultOwnershipType="self" resourceTypeId={register} categories={(types.data?.data||[]).filter(t=>t.resource_type_id===register).map(t=>({id:t.id,name:t.name,sub_category:t.sub_category,resource_type_id:t.resource_type_id}))} onSubmit={registerAsset} isSubmitting={registering}/>)}
 </main>;
}
