import React, {useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {useAuth} from '@/context/AuthContext';
import {rememberDestination} from '@/utils/navigation/entry';
import {rfpRpc,rfpError} from './rfpLifecycle';
import {InlineLoader} from '@/components/common/loaders/UnifiedLoader';
import {useVaNiToast} from '@/components/common/toast/VaNiToast';
import {setLandingPerspective} from '@/utils/perspective/sideActivation';
export default function VendorNextSteps({cnak,secret,awarded,buyerPreparing=false}:{cnak:string;secret:string;awarded:boolean;buyerPreparing?:boolean}){
 const {isAuthenticated,currentTenant,isLive,perspective,checkOnboardingStatus}=useAuth();
 const {addToast}=useVaNiToast();
 const navigate=useNavigate(); const [busy,setBusy]=useState(false),[error,setError]=useState('');
 function signIn(register:boolean){const path=`/quote/${encodeURIComponent(cnak)}/${encodeURIComponent(secret)}`;rememberDestination(path);sessionStorage.setItem('contractnest_auth_redirect',path);navigate(register?`/register?source=rfp&ref=${encodeURIComponent(cnak)}`:'/login');}
 async function track(){if(busy||!currentTenant)return;setBusy(true);try{const result=await rfpRpc('rfp_track_request',{p_cnak:cnak,p_secret:secret,p_tenant:currentTenant.id});await checkOnboardingStatus();if(typeof result.contract?.is_live==='boolean')localStorage.setItem('is_live_environment',String(result.contract.is_live));setLandingPerspective('revenue');window.location.assign('/requests');}catch(e){addToast({type:'error',title:'Request not connected',message:rfpError(e)});setBusy(false);}}
 async function prepare(){if(busy)return;setBusy(true);setError('');try{const result=await rfpRpc('rfp_vendor_prepare',{p_cnak:cnak,p_secret:secret,p_tenant:currentTenant?.id,p_live:isLive});const saved=result.data??result;if(!saved.id)throw Error('Contract draft was not confirmed.');navigate(`/contracts/experience/create?relationship=client&draft=${encodeURIComponent(saved.id)}`);}catch(e){setError(rfpError(e));}finally{setBusy(false);}}
 if(awarded&&buyerPreparing)return <section className="rfp-paper"><h2>Your proposal has been selected.</h2><p>The buyer has already started the linked agreement. They will send it for your review; there is no need to create another draft.</p><p>Award alone does not activate a contract or confirm payment.</p>{isAuthenticated?<button className="rfp-button primary" disabled={busy||!currentTenant} onClick={()=>void track()}>Track this request</button>:<button className="rfp-button primary" onClick={()=>signIn(true)}>Sign up to track this request</button>}</section>;
 return <section className="rfp-paper"><h2>{awarded?'Your proposal has been selected.':'Keep this opportunity connected.'}</h2><p>{awarded?'Prepare the agreement from your submitted commitments. The buyer reviews it before acceptance; award alone does not activate services or confirm payment.':'Track your submitted proposal, buyer decisions and next steps. No business onboarding is required. Signup is optional.'}</p>
 {!isAuthenticated?<div className="rfp-row"><button type="button" className="rfp-button primary" onClick={()=>signIn(true)}>Sign up to track this request</button><button type="button" className="rfp-button" onClick={()=>signIn(false)}>Already registered? Sign in</button></div>:awarded?<><p>Workspace: <strong>{currentTenant?.name||'Choose a workspace'}</strong>. Use the account with the verified email or mobile that received the invitation.</p>{perspective!=='revenue'?<p>Switch to Revenue to prepare an agreement as the service provider.</p>:<button type="button" disabled={busy||!currentTenant} className="rfp-button primary" onClick={()=>void prepare()}>{busy?'Opening agreement…':'Prepare agreement →'}</button>}</>:<><button type="button" className="rfp-button primary" disabled={busy||!currentTenant} onClick={()=>void track()}>{busy?'Connecting request…':'Track this request →'}</button><p>Optional: <button type="button" className="rfp-button" onClick={()=>navigate('/onboarding')}>Explore business setup</button></p></>}
 {busy&&<InlineLoader text="Opening your linked agreement"/>}{error&&<p className="rfp-error" role="alert">{error}</p>}</section>;
}
