// src/components/VaNi/bbb/WebsiteScrapingForm.tsx
// File 6/13 - BBB Website Scraping Results Component

import React, { useState } from 'react';
import { useTheme } from '../../../contexts/ThemeContext';
import { Card, CardHeader, CardTitle, CardContent } from '../../../components/ui/card';
import { 
  Globe, 
  CheckCircle,
  Edit3,
  Save,
  AlertCircle,
  Sparkles,
  ExternalLink
} from 'lucide-react';

interface WebsiteScrapingFormProps {
  websiteUrl: string;
  generatedDescription: string;
  onSave: (description: string) => void;
  isSaving?: boolean;
}

const WebsiteScrapingForm: React.FC<WebsiteScrapingFormProps> = ({
  websiteUrl,
  generatedDescription,
  onSave,
  isSaving = false
}) => {
  const { isDarkMode, currentTheme } = useTheme();
  const colors = isDarkMode ? currentTheme.darkMode.colors : currentTheme.colors;

  const [description, setDescription] = useState(generatedDescription);
  const [isEditing, setIsEditing] = useState(false);

  const handleSave = () => {
    if (description.trim().length === 0) {
      return;
    }
    onSave(description.trim());
  };

  return (
    <Card
      style={{
        backgroundColor: colors.utility.primaryBackground,
        borderColor: `${colors.utility.primaryText}20`
      }}
    >
      <CardHeader
        style={{
          background: `linear-gradient(135deg, ${colors.brand.primary}15 0%, ${colors.brand.secondary}15 100%)`,
          borderBottom: `1px solid ${colors.utility.primaryText}15`
        }}
      >
        <CardTitle>
          <div className="flex items-start justify-between">
            <div className="flex items-start space-x-3 flex-1">
              <div
                className="p-2 rounded-lg"
                style={{
                  backgroundColor: `${colors.semantic.success}20`
                }}
              >
                <Sparkles className="w-6 h-6" style={{ color: colors.semantic.success }} />
              </div>
              <div className="flex-1">
                <h3 className="text-lg font-bold flex items-center space-x-2" style={{ color: colors.utility.primaryText }}>
                  <span>Your Profile has been generated by VaNi</span>
                </h3>
                <div className="flex items-center space-x-2 mt-2">
                  <Globe className="w-4 h-4" style={{ color: colors.brand.secondary }} />
                  <a
                    href={websiteUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-sm font-medium hover:underline flex items-center space-x-1"
                    style={{ color: colors.brand.secondary }}
                  >
                    <span className="truncate max-w-md">{websiteUrl}</span>
                    <ExternalLink className="w-3 h-3 flex-shrink-0" />
                  </a>
                </div>
              </div>
            </div>
            {!isEditing && (
              <button
                onClick={() => setIsEditing(true)}
                className="flex items-center space-x-2 px-4 py-2 rounded-lg font-medium transition-all hover:opacity-80"
                style={{
                  backgroundColor: colors.utility.secondaryBackground,
                  color: colors.brand.primary,
                  border: `1px solid ${colors.brand.primary}40`
                }}
                disabled={isSaving}
              >
                <Edit3 className="w-4 h-4" />
                <span>Edit</span>
              </button>
            )}
          </div>
        </CardTitle>
      </CardHeader>

      <CardContent className="p-6 space-y-6">
        {/* Success Message */}
        <div
          className="p-4 rounded-lg"
          style={{
            backgroundColor: `${colors.semantic.success}15`,
            border: `1px solid ${colors.semantic.success}40`
          }}
        >
          <div className="flex items-start space-x-3">
            <CheckCircle className="w-5 h-5 flex-shrink-0 mt-0.5" style={{ color: colors.semantic.success }} />
            <div>
              <p className="text-sm font-semibold mb-1" style={{ color: colors.utility.primaryText }}>
                Profile Successfully Generated
              </p>
              <p className="text-xs" style={{ color: colors.utility.secondaryText }}>
                VaNi has analyzed your website and created a professional business description. 
                You can edit this description or save it directly to your BBB profile.
              </p>
            </div>
          </div>
        </div>

        {/* Generated Description */}
        <div>
          <label
            htmlFor="generated_description"
            className="block text-sm font-medium mb-2"
            style={{ color: colors.utility.primaryText }}
          >
            Generated Description *
          </label>
          
          {isEditing ? (
            <div className="space-y-3">
              <textarea
                id="generated_description"
                rows={8}
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                placeholder="Brief description of the business (1-2 sentences)"
                className="w-full p-3 border rounded-lg focus:outline-none focus:ring-2 transition-all resize-none"
                style={{
                  borderColor: `${colors.utility.secondaryText}40`,
                  backgroundColor: colors.utility.secondaryBackground,
                  color: colors.utility.primaryText,
                  '--tw-ring-color': colors.brand.primary
                } as React.CSSProperties}
                disabled={isSaving}
              />
              <div className="flex justify-between items-center">
                <p className="text-xs" style={{ color: colors.utility.secondaryText }}>
                  {description.length} characters
                </p>
                {description.length > 0 && description.length < 50 && (
                  <p className="text-xs flex items-center space-x-1" style={{ color: colors.semantic.warning }}>
                    <AlertCircle className="w-3 h-3" />
                    <span>Description seems too short</span>
                  </p>
                )}
              </div>
              <div className="flex space-x-3">
                <button
                  type="button"
                  onClick={() => {
                    setDescription(generatedDescription);
                    setIsEditing(false);
                  }}
                  className="flex-1 px-4 py-2 rounded-lg font-medium transition-all hover:opacity-80"
                  style={{
                    backgroundColor: colors.utility.secondaryBackground,
                    color: colors.utility.primaryText,
                    border: `1px solid ${colors.utility.primaryText}30`
                  }}
                  disabled={isSaving}
                >
                  Cancel
                </button>
                <button
                  type="button"
                  onClick={() => setIsEditing(false)}
                  className="flex-1 px-4 py-2 rounded-lg font-medium transition-all hover:opacity-90"
                  style={{
                    backgroundColor: colors.brand.primary,
                    color: '#FFFFFF'
                  }}
                  disabled={isSaving}
                >
                  Done Editing
                </button>
              </div>
            </div>
          ) : (
            <div
              className="p-4 rounded-lg border"
              style={{
                backgroundColor: colors.utility.secondaryBackground,
                borderColor: `${colors.utility.primaryText}20`
              }}
            >
              <p
                className="text-sm leading-relaxed whitespace-pre-wrap"
                style={{ color: colors.utility.primaryText }}
              >
                {description}
              </p>
            </div>
          )}
        </div>

        {/* Info Box */}
        {!isEditing && (
          <div
            className="p-4 rounded-lg"
            style={{
              backgroundColor: `${colors.semantic.info}15`,
              border: `1px solid ${colors.semantic.info}40`
            }}
          >
            <div className="flex items-start space-x-3">
              <Sparkles className="w-5 h-5 flex-shrink-0 mt-0.5" style={{ color: colors.semantic.info }} />
              <div>
                <p className="text-sm font-semibold mb-1" style={{ color: colors.utility.primaryText }}>
                  What happens next?
                </p>
                <p className="text-xs" style={{ color: colors.utility.secondaryText }}>
                  When you save this profile, VaNi will automatically generate semantic clusters 
                  and keywords to make your business easily discoverable in the BBB directory. 
                  This profile will be searchable by other BBB members.
                </p>
              </div>
            </div>
          </div>
        )}

        {/* Save Button */}
        {!isEditing && (
          <button
            type="button"
            onClick={handleSave}
            disabled={isSaving || description.trim().length === 0}
            className="w-full flex items-center justify-center space-x-2 px-6 py-4 rounded-lg font-semibold text-white transition-all hover:opacity-90 disabled:opacity-50 disabled:cursor-not-allowed"
            style={{
              background: `linear-gradient(to right, ${colors.brand.primary}, ${colors.brand.secondary})`
            }}
          >
            {isSaving ? (
              <>
                <div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin" />
                <span>Saving your profile...</span>
              </>
            ) : (
              <>
                <Save className="w-5 h-5" />
                <span>Save my profile</span>
              </>
            )}
          </button>
        )}
      </CardContent>
    </Card>
  );
};

export default WebsiteScrapingForm;